name: Update cluster node

on:
  schedule:
    - cron: '0 12 */15 * *'
  workflow_dispatch:

jobs:
  upgrade-node:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Discover last kubernetes version
        id: discover_version
        run: |
          kubernetes_version=$(az aks get-versions --location brazilsouth --query 'orchestrators[-1].orchestratorVersion')
          
          echo "::set-output name=kubernetes_version::$kubernetes_version"
          
      - name: Print version choosed
        run: |
          echo "${{ steps.discover_version.outputs.kubernetes_version }}"


      - name: Upgrade node images
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: az aks upgrade --resource-group ${{secrets.RESOURCE_GROUP_NAME}} --name ${{secrets.AKS_CLUSTER_NAME}} --no-wait --kubernetes-version ${{ steps.discover_version.outputs.kubernetes_version }}
